### ISSUE TITLE
GoogleJsonResponseException: 400 Bad Request "The specified time range is empty."

### ISSUE THREAD

**Issue by quaddy-services** [quaddy-services/DeadlineReminder#5]
`com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "calendar",
    "location" : "timeMax",
    "locationType" : "parameter",
    "message" : "The specified time range is empty.",
    "reason" : "timeRangeEmpty"
  } ],
  "message" : "The specified time range is empty."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:451) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1089) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:549) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:482) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:599) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at de.quaddy_services.deadlinereminder.extern.GoogleSync.push(GoogleSync.java:333) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at de.quaddy_services.deadlinereminder.extern.GoogleSync.push(GoogleSync.java:176) ~[DeadlineReminder-jar-with-dependencies.jar:na]
	at de.quaddy_services.deadlinereminder.extern.GoogleSync$1.run(GoogleSync.java:84) ~[DeadlineReminder-jar-with-dependencies.jar:na]

`

**Comment by quaddy-services** [comment]
start=GenericData{classInfo=[date, dateTime, timeZone], {dateTime=2019-10-25T00:00:00.000+02:00}}
end=GenericData{classInfo=[date, dateTime, timeZone], {dateTime=2019-10-24T19:30:00.000+02:00}}
24.10.2019 19:30 Ankunft

**Comment by quaddy-services** [comment]
Fixed.
